Install Docker from `edge`
The current version (v23.0.6-r4) causes issues where fetching from a
Docker repository fails with the following error:

    ERROR: http: invalid Host header